# Form implementation generated from reading ui file 'D:\Python\Arduino Project\LED_RBG_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LED_RBG_GUI(object):
    def setupUi(self, LED_RBG_GUI):
        LED_RBG_GUI.setObjectName("LED_RBG_GUI")
        LED_RBG_GUI.resize(504, 131)
        self.gridLayout = QtWidgets.QGridLayout(LED_RBG_GUI)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Red_value = QtWidgets.QSpinBox(LED_RBG_GUI)
        self.Red_value.setMaximum(255)
        self.Red_value.setObjectName("Red_value")
        self.horizontalLayout.addWidget(self.Red_value)
        self.Green_value = QtWidgets.QSpinBox(LED_RBG_GUI)
        self.Green_value.setMaximum(255)
        self.Green_value.setObjectName("Green_value")
        self.horizontalLayout.addWidget(self.Green_value)
        self.Blue_value = QtWidgets.QSpinBox(LED_RBG_GUI)
        self.Blue_value.setMaximum(255)
        self.Blue_value.setObjectName("Blue_value")
        self.horizontalLayout.addWidget(self.Blue_value)
        self.pushButton = QtWidgets.QPushButton(LED_RBG_GUI)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(LED_RBG_GUI)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)

        self.retranslateUi(LED_RBG_GUI)
        QtCore.QMetaObject.connectSlotsByName(LED_RBG_GUI)

    def retranslateUi(self, LED_RBG_GUI):
        _translate = QtCore.QCoreApplication.translate
        LED_RBG_GUI.setWindowTitle(_translate("LED_RBG_GUI", "Form"))
        self.pushButton.setText(_translate("LED_RBG_GUI", "Change Color!"))
        self.label.setText(_translate("LED_RBG_GUI", "         Red                       Green                       Blue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LED_RBG_GUI = QtWidgets.QWidget()
    ui = Ui_LED_RBG_GUI()
    ui.setupUi(LED_RBG_GUI)
    LED_RBG_GUI.show()
    sys.exit(app.exec())
